name: "Build and test for release"
description: "A common build and test action for all subsequent actions to run prior to their runs."
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash

    - uses: actions/checkout@v3

    - name: Add fustfmt
      run: rustup component add rustfmt

    - name: Build for release
      run: cargo build --release

    - name: Run unit tests
      run: cargo test --quiet

    - name: Run formatter
      run: cargo fmt --all -- --check
