[package]
name = "joey-mckenzie-tech"
version = "0.1.0"
edition = "2021"
publish = false
license-file = "./LICENSE"

[lib]
name = "spotify"
path = "src/serverless/lib.rs"

[[bin]]
name = "serverless_debug"
path = "src/serverless/debug.rs"

[dependencies]
# framework crates
tokio = { version = "1", features = ["full"] }

# web crates
shuttle-service = { version = "0.11", features = ["web-axum"] }
shuttle-secrets = "0.11"
axum = { version = "0.6", features = ["json"] }
tower-http = { version = "0.4", features = ["limit", "timeout", "cors"] }
hyper = "0.14"

# utilitiy crates
sync_wrapper = "0.1.2"
tracing = "0.1"
serde = { version = "1.0", features = ["serde_derive"] }
reqwest = { version = "0.11", features = ["json"] }
thiserror = "1"

# crates for running debug
dotenv = "0.15"
tracing-subscriber = "0.3"
derive_builder = "0.12.0"
