[package]
name = "joey-mckenzie-tech"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls"] }
tera = "1"
serde = { version = "1", features = ["derive"] }

tower = "0.4"
tower-http = { version = "0.4", features = ["fs"] }
anyhow = "1"
pulldown-cmark = "0.9"
gray_matter = { version = "0.2", features = ["yaml"] }
dotenvy = "0.15.7"
thiserror = "1"

[build-dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
