[package]
name = "joey-mckenzie-tech"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls"] }
tera = "1"
serde = { version = "1.0.188", features = ["derive"] }

tower = "0.4"
tower-http = { version = "0.4", features = ["fs"] }
anyhow = "1.0.75"
pulldown-cmark = "0.9.3"
