# fly.toml app configuration file generated for joey-mckenzie-tech on 2023-11-14T21:12:22-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "joey-mckenzie-tech"
primary_region = "sjc"
console_command = "php /var/www/html/artisan tinker"

[processes]
app = ""
ssr = "php /var/www/html/artisan inertia:start-ssr"

[build]
[build.args]
NODE_VERSION = "18"
PHP_VERSION = "8.2"

[env]
APP_ENV = "production"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
SESSION_DRIVER = "cookie"
SESSION_SECURE_COOKIE = "true"
SSR_URL = "ssr.process.<yourAppNameHerePlease>.internal:13714"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
