# fly.toml app configuration file generated for rust-blog on 2023-09-06T22:58:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rust-blog"
primary_region = "sjc"

[build]

[env]
RUST_ENV = "production"
SQLX_OFFLINE = "true"
PORT = "80"
BASE_URL = "https://joeymckenzie.tech"

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
