[env] ## tells cargo make that we're in the context of a Cargo workspace
DOCKER_BUILD_TAG = "joey_mckenzie_tech"

CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.run-server]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-x", "run"]

[tasks.docker-build]
command = "docker"
env_files = [".env"]
args = [
    "build",
    ".",
    "--build-arg",
    "PORT=${PORT}",
    "--build-arg",
    "SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}",
    "--build-arg",
    "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}",
    "--build-arg",
    "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}",
    "--build-arg",
    "TIMEOUT_DURATION_SECONDS=${TIMEOUT_DURATION_SECONDS}",
    "--build-arg",
    "LOG_LEVEL=${LOG_LEVEL}",
    "-t",
    "${DOCKER_BUILD_TAG}",
]

[tasks.docker-run]
command = "docker"
env_files = [".env"]
args = [
    "run",
    "-d",
    "-p",
    "${PORT}:${PORT}",
    "--name",
    "${DOCKER_BUILD_TAG}",
    "-it",
    "${DOCKER_BUILD_TAG}",
]

[tasks.docker-stop]
command = "docker"
args = ["stop", "${DOCKER_BUILD_TAG}"]

[tasks.docker-start]
command = "docker"
args = ["stop", "${DOCKER_BUILD_TAG}"]
