[env] ## tells cargo make that we're in the context of a Cargo workspace
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config] ## we want most/all of our tasks to run in the context of a workspace
default_to_workspace = false

[tasks.blog-serverless]
install_crate = "cargo-shuttle"
command = "cargo"
args = ["shuttle", "run"]

[tasks.samples-serverless-rust]
install_crate = "cargo-shuttle"
cwd = "samples/serverless-rust-with-shuttle"
command = "cargo"
args = ["shuttle", "run"]
