[tasks.default]
dependencies = ["dev"]

[tasks.dev]
script = "cargo leptos watch & find src/ | entr -s 'cargo make fmt && npm run tailwind:compile'"

[tasks.fmt]
command = "cargo"
args = ["fmt"]
dependencies = ["leptosfmt"]

[tasks.leptosfmt]
install_crate = "leptosfmt"
command = "leptosfmt"
args = ["src/*.rs", "src/**/*.rs"]

[tasks.build]
command = "cargo"
args = ["leptos", "build", "--release", "-vv"]

[tasks.content]
command = "cargo"
args = ["run", "--bin", "content", "--features", "content"]

[tasks.prepare]
command = "cargo"
args = ["sqlx", "prepare", "--", "--all-targets", "--all-features"]

[tasks.deploy]
command = "fly"
env_files = ["./.env.production"]
args = [
  "deploy",
  "--build-arg",
  "SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}",
  "--build-arg",
  "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}",
  "--build-arg",
  "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}",
  "--build-arg",
  "APP_URL=${APP_URL}",
  "--build-arg",
  "COMMIT_SHA=${COMMIT_SHA}",
  "--build-arg",
  "DATABASE_URL=${DATABASE_URL}",
]

[tasks.docker-build]
command = "docker"
env_files = ["./.env"]
args = [
  "build",
  "--build-arg",
  "SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}",
  "--build-arg",
  "SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}",
  "--build-arg",
  "SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}",
  "--build-arg",
  "APP_URL=${APP_URL}",
  "--build-arg",
  "DATABASE_URL=${DATABASE_URL}",
  "-t",
  "blog:latest",
  ".",
]

[tasks.docker-run]
command = "docker"
args = [
  "run",
  "-d",
  "--name",
  "blog",
  "-p",
  "8080:8080",
  "--env-file",
  "./.env",
  "blog:latest",
]

[tasks.docker-stop]
command = "docker"
args = ["stop", "blog"]

[tasks.docker-rm]
command = "docker"
args = ["rm", "blog"]

[tasks.docker-restart]
command = "docker"
dependencies = ["docker-stop", "docker-rm", "docker-build", "docker-run"]

[tasks.prepare-hooks]
command = "git"
args = ["config", "core.hookspath", ".githooks"]

[tasks.secrets]
command = "fly"
args = ["secrets", "import", "<", ".env.production"]
