SPOTIFY_REFRESH_TOKEN = "AQD1AaghXZP1qB5lBgBxsucHT8Yr_ddxmiO2ec3MFDpR3uQvIIQD_JPSQxWyWMy73FcfQQtnbG2ZJCj4tJOUdZVG5yucLczkXnRcrbRI1Ce2NJmTyHzO8-qGUb39NWmFj0w"
SPOTIFY_CLIENT_ID = "7e412c0fccfa496c86f7af7fb86661b4"
SPOTIFY_CLIENT_SECRET = "ee3a8072ddf1466b88f650fa39b0d2ce"
TIMEOUT_DURATION_SECONDS = "10"
