# Note: mold is lld's modern successor only available on Linux/macOS
# Eventually will upgrade to use mold in place of lld (not on Debian 11 right now)

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
