# Note: mold is lld's modern successor only available on Linux/macOS
# Read more about the project here: https://github.com/rui314/mold
# if your gcc version is recent enough, you can remove clang as your linker
# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
