log_level = "info"

[server]
timeout_duration_seconds = 10
port = 80
cors_origins = ["https://joeymckenzie.tech", "https://www.joeymckenzie.tech"]
top_posts_threshold = 3

[database]
max_db_connections = 50
