name: Build astro site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Enable pnpm
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Install turbo
        run: pnpm install turbo --global

      # TODO: Link to vercel remote cache here before running build

      - name: Run build and lint targets
        run: turbo build lint
