name: Build and test serverless functions for release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1

      - name: Install protoc
        run: |
          ARCH="linux-x86_64" && \
          VERSION="22.2" && \
          curl -OL "https://github.com/protocolbuffers/protobuf/releases/download/v$VERSION/protoc-$VERSION-$ARCH.zip" && \
          sudo unzip -o "protoc-$VERSION-$ARCH.zip" bin/protoc "include/*" -d /usr/local && \
          rm -f "protoc-$VERSION-$ARCH.zip"

      - name: Build for release
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --quiet

      - name: Add rust fmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run rust formatter checks
        run: cargo fmt --all -- --check
