name: Build and test for release

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1

      - name: Build for release
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --quiet

      - name: Add rust fmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run rust formatter checks
        run: cargo fmt --all -- --check
