name: Build and test serverless functions for release

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1

      - name: Install protoc
        run: scripts/install.sh

      - name: Build for release
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --quiet

      - name: Add rust fmt
        run: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Run rust formatter checks
        run: cargo fmt --all -- --check

      - name: Deploy to fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
