name: Build and test serverless functions for release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1

      - name: Install protoc
        run: |
          curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-linux-x86_64.zip \
            && sudo unzip -o protoc-21.9-linux-x86_64.zip -d /usr/local bin/protoc \
            && sudo unzip -o protoc-21.9-linux-x86_64.zip -d /usr/local 'include/*' \
            && rm -f protoc-21.9-linux-x86_64.zip

      - name: Build for release
        run: cargo build --release

      - name: Run unit tests
        run: cargo test --quiet

      - name: Run rust formatter checks
        run: cargo fmt --all -- --check
