name: CI

on: [push]

# We won't actually use this explicitly in the CI run for now,
# the framework requires they're available during compilation
env:
  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN}}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID}}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET}}
  VERCEL_GIT_COMMIT_SHA: ${{ secrets.VERCEL_GIT_COMMIT_SHA}}
  DATABASE_URL: ${{ secrets.DATABASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build and lint
        run: pnpm run ci
