name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  FUNCTIONS_DIR: .netlify
  PUBLISH_DIR: dist

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build and lint
        run: bun run ci

      - name: Link to Netlify
        run: bunx netlify link --name {{ github.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify
        run: bunx netlify deploy --site {{ github.NETLIFY_SITE_ID }} --auth {{ github.NETLIFY_DEPLOY_TOKEN }} --functions {{ env.FUNCTIONS_DIR }} --dir {{ env.PUBLISH_DIR }} --prod
