name: CI

on: [ push ]

env:
  SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN}}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID}}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET}}
  VERCEL_GIT_COMMIT_SHA: ${{ secrets.VERCEL_GIT_COMMIT_SHA}}
  DATABASE_URL: ${{ secrets.DATABASE_URL}}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build and lint
        run: bun run ci
