name: Deploy to shuttle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build dependencies
        run: cargo build --release

      # TODO: This is taking way longer than expected, should look into this eventually

      # - name: Install cargo-shuttle
      #   run: cargo install cargo-shuttle

      # - name: Authenticate with shuttle
      #   run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}

      # - name: Deploy to shuttle
      #   run: cargo shuttle deploy
