name: Deploy to Fly

on:
  push:
    branches: ['poc/leptos']

env:
  APP_URL: https://joeymckenzie.tech
  SQLX_OFFLINE: true

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && ${{ !github.actor == 'dependabot[bot]' }}
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/checkout@v3

      - name: Deploy to fly
        run: |
          flyctl deploy --remote-only \
            --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --build-arg APP_URL=${{ env.APP_URL }}
            --build-arg SQLX_OFFLINE=${{ env.SQLX_OFFLINE }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
