name: Deploy to Fly

on:
    workflow_run:
        workflows: ['Server CI']
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        name: Deploy application
        steps:
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - uses: actions/checkout@v3

            - name: Deploy to fly
              run: flyctl deploy --build-arg BUILD_COMMIT_SHA=${{ github.sha }} --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
                  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  DB_DATABASE: ${{ secrets.DB_DATABASE }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  MYSQL_ATTR_SSL_CA: ${{ secrets.MYSQL_ATTR_SSL_CA }}
