name: Deploy to shuttle

on:
  workflow_run:
    workflows: ['Build and test serverless functions for release']
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rui314/setup-mold@v1

      - name: Install protoc
        run: scripts/install.sh

      - name: Install cargo-shuttle
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-shuttle

      - name: Authenticate with shuttle
        run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}

      - name: Deploy to shuttle
        run: cargo shuttle deploy
