name: Deploy to Fly

on:
    workflow_run:
        workflows: ['Server CI']
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        name: Deploy application
        steps:
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - uses: actions/checkout@v3

            - name: Deploy to fly
              run: |
                  flyctl deploy \
                    --build-arg BUILD_COMMIT_SHA=${{ github.sha }} \
                    --build-arg DB_CONNECTION=${{ secrets.DB_CONNECTION }} \
                    --build-arg DB_HOST=${{ secrets.DB_HOST }} \
                    --build-arg DB_PORT=${{ secrets.DB_PORT }} \
                    --build-arg DB_DATABASE=${{ secrets.DB_DATABASE }} \
                    --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
                    --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
                    --build-arg MYSQL_ATTR_SSL_CA=${{ secrets.MYSQL_ATTR_SSL_CA }} \
                    --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
