name: Deploy to shuttle

on:
  workflow_run:
    workflows: ['Build and test serverless functions for release']
    types:
      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install protoc
        run: |
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v21.9/protoc-21.9-linux-x86_64.zip \
          && sudo unzip -o protoc-21.9-linux-x86_64.zip -d /usr/local bin/protoc \
          && sudo unzip -o protoc-21.9-linux-x86_64.zip -d /usr/local 'include/*' \
          rm -f protoc-21.9-linux-x86_64.zip

      - name: Install cargo-shuttle
        run: |
          cargo install cargo-quickinstall
          cargo quickinstall cargo-shuttle

      - name: Authenticate with shuttle
        run: cargo shuttle login --api-key ${{ secrets.SHUTTLE_API_KEY }}

      - name: Deploy to shuttle
        run: cargo shuttle deploy
