name: Deploy to Forge

on:
  workflow_run:
    workflows: ['Run CI']
    types:
      - completed

jobs:
  forge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    name: Deploy application
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install composer dependencies
        run: composer install

      - name: Run migrations
        run: php artisan migrate --force

      - name: Sync content
        run: php artisan content:sync

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
