name: Trigger Forge deploy

on:
    workflow_run:
        workflows: ['Inertia CI']
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        name: Deploy application
        steps:
            - uses: actions/checkout@v3

            - name: Ping deploy URL
              run: curl -l ${{ secrets.FORGE_DEPLOY_URL }}
