name: Deploy to Fly

on:
    workflow_run:
        workflows: ['Fly CI']
        types:
            - completed

jobs:
    build:
        name: Deploy application
        runs-on: ubuntu-latest
        steps:
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - uses: actions/checkout@v3

            - name: Deploy to fly
              run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
