name: Deploy to Fly

on:
  push:
    branches: ['archive/leptos']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Update build commit
        run: |
          flyctl secrets set --stage COMMIT_SHA=${{ github.sha }}

      - name: Deploy to fly
        run: |
          flyctl deploy --remote-only \
          --build-arg SPOTIFY_REFRESH_TOKEN=${{ secrets.SPOTIFY_REFRESH_TOKEN }} \
          --build-arg SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }} \
          --build-arg SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          --build-arg APP_URL=${{ env.APP_URL }} \
          --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}
          APP_URL: https://joeymckenzie.tech
