name: Server CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              id: setup-php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'

            - name: Install composer dependencies
              run: composer install

            - name: Lint and test
              run: composer run ci
              env:
                  DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
                  DB_HOST: ${{ secrets.DB_HOST }}
                  DB_PORT: ${{ secrets.DB_PORT }}
                  DB_DATABASE: ${{ secrets.DB_DATABASE }}
                  DB_USERNAME: ${{ secrets.DB_USERNAME }}
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                  MYSQL_ATTR_SSL_CA: ${{ secrets.MYSQL_ATTR_SSL_CA }}
