name: Server CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install composer dependencies
        run: composer install

      - name: Lint and test
        run: composer run ci
